/**
 * bundle-canon.ts — build script for the bundled `docs` corpus.
 *
 * Reads every canon/**\/*.md, parses minimal frontmatter (uri, title, tags),
 * and writes src/canon-bundle.generated.ts. The `docs` tool searches this
 * bundle in-process — no runtime call to oddkit (or any other upstream).
 *
 * Run:   npx tsx scripts/bundle-canon.ts
 * Check: npx tsx scripts/bundle-canon.ts --check   (exit 1 on drift)
 *
 * Pattern: ptxprint-mcp bundled progressive-disclosure docs (kitchen
 * rail/6-learned/2026-09-05-ptxprint-docs-v2-progressive-disclosure).
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const canonDir = join(rootDir, "canon");
const outPath = join(rootDir, "src", "canon-bundle.generated.ts");

function walk(dir: string): string[] {
  return readdirSync(dir)
    .sort()
    .flatMap((n) => {
      const p = join(dir, n);
      return statSync(p).isDirectory() ? walk(p) : p.endsWith(".md") ? [p] : [];
    });
}

function frontmatter(src: string): Record<string, string> {
  const m = /^---\n([\s\S]*?)\n---/.exec(src);
  const out: Record<string, string> = {};
  if (!m) return out;
  for (const line of m[1].split("\n")) {
    const kv = /^([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (kv) out[kv[1]] = kv[2].trim();
  }
  return out;
}

const docs = walk(canonDir).map((p) => {
  const path = relative(rootDir, p).split("\\").join("/");
  const content = readFileSync(p, "utf-8");
  const fm = frontmatter(content);
  const uri = fm.uri || `klappy://${path.replace(/\.md$/, "")}`;
  const title = (fm.title || path).replace(/^["']|["']$/g, "");
  let tags: string[] = [];
  try {
    tags = fm.tags ? JSON.parse(fm.tags) : [];
  } catch {
    tags = [];
  }
  return { uri, path, title, tags, content };
});

const out =
  "// AUTO-GENERATED by scripts/bundle-canon.ts — do not edit by hand.\n" +
  "// Regenerate: npx tsx scripts/bundle-canon.ts\n\n" +
  "export interface BundledDoc { uri: string; path: string; title: string; tags: string[]; content: string }\n\n" +
  `export const CANON_BUNDLE: BundledDoc[] = ${JSON.stringify(docs, null, 0)};\n`;

if (process.argv.includes("--check")) {
  const cur = existsSync(outPath) ? readFileSync(outPath, "utf-8") : "";
  if (cur !== out) {
    console.error("canon bundle drift: run `npx tsx scripts/bundle-canon.ts`");
    process.exit(1);
  }
  console.log(`canon bundle up to date (${docs.length} docs)`);
} else {
  writeFileSync(outPath, out);
  console.log(`wrote ${relative(rootDir, outPath)} (${docs.length} docs)`);
}
